export const initRecipes = [
  {
    id: 1,
    imageURL: "https://source.unsplash.com/800x600/?pasta",
    title: "Spaghetti Carbonara",
    readyInMinutes: 25,
    healthScore: 70,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "200g spaghetti" },
      { id: 2, original: "100g pancetta" },
      { id: 3, original: "2 large eggs" },
      { id: 4, original: "50g pecorino cheese" },
      { id: 5, original: "2 cloves garlic" },
      { id: 6, original: "Salt and black pepper to taste" },
    ],
    instructions:
      "Step 1: Cook spaghetti. Step 2: Fry pancetta with garlic. Step 3: Beat eggs and mix with cheese. Step 4: Combine all and season.",
  },
  {
    id: 2,
    imageURL: "https://source.unsplash.com/800x600/?salad",
    title: "Caesar Salad",
    readyInMinutes: 20,
    healthScore: 85,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "1 romaine lettuce" },
      { id: 2, original: "50g croutons" },
      { id: 3, original: "30g parmesan cheese" },
      { id: 4, original: "1 clove garlic" },
      { id: 5, original: "1 egg yolk" },
      { id: 6, original: "2 tbsp olive oil" },
      { id: 7, original: "1 tsp Worcestershire sauce" },
      { id: 8, original: "Juice of 1 lemon" },
      { id: 9, original: "Salt and pepper to taste" },
    ],
    instructions:
      "Step 1: Prepare dressing with egg yolk, garlic, oil, Worcestershire sauce, lemon juice, salt, and pepper. Step 2: Toss lettuce with dressing. Step 3: Top with croutons and shaved parmesan.",
  },
  {
    id: 3,
    imageURL: "https://source.unsplash.com/800x600/?burger",
    title: "Classic Beef Burger",
    readyInMinutes: 30,
    healthScore: 60,
    difficulty: "Medium",
    extendedIngredients: [
      { id: 1, original: "500g ground beef" },
      { id: 2, original: "4 burger buns" },
      { id: 3, original: "4 slices cheddar cheese" },
      { id: 4, original: "1 tomato" },
      { id: 5, original: "Lettuce leaves" },
      { id: 6, original: "1 onion" },
      { id: 7, original: "Salt and pepper to taste" },
      { id: 8, original: "Ketchup and mustard" },
    ],
    instructions:
      "Step 1: Form beef into patties and season. Step 2: Grill patties. Step 3: Assemble burgers with buns, cheese, tomato, lettuce, onion, ketchup, and mustard.",
  },
  {
    id: 4,
    imageURL: "https://source.unsplash.com/800x600/?sushi",
    title: "Sushi Rolls",
    readyInMinutes: 50,
    healthScore: 75,
    difficulty: "Hard",
    extendedIngredients: [
      { id: 1, original: "2 cups sushi rice" },
      { id: 2, original: "4 sheets nori" },
      { id: 3, original: "200g fresh salmon" },
      { id: 4, original: "1 cucumber" },
      { id: 5, original: "Soy sauce" },
      { id: 6, original: "Pickled ginger" },
      { id: 7, original: "Wasabi" },
    ],
    instructions:
      "Step 1: Prepare sushi rice. Step 2: Slice salmon and cucumber. Step 3: Place nori on mat, add rice, salmon, and cucumber. Step 4: Roll tightly and slice. Serve with soy sauce, ginger, and wasabi.",
  },
  {
    id: 5,
    imageURL: "https://source.unsplash.com/800x600/?pancakes",
    title: "Fluffy Pancakes",
    readyInMinutes: 20,
    healthScore: 65,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "1 cup all-purpose flour" },
      { id: 2, original: "2 tbsp sugar" },
      { id: 3, original: "1 tbsp baking powder" },
      { id: 4, original: "1/2 tsp salt" },
      { id: 5, original: "1 cup milk" },
      { id: 6, original: "1 egg" },
      { id: 7, original: "2 tbsp melted butter" },
      { id: 8, original: "Maple syrup" },
    ],
    instructions:
      "Step 1: Mix dry ingredients. Step 2: Whisk wet ingredients and combine with dry. Step 3: Cook pancakes on griddle. Step 4: Serve with maple syrup.",
  },
  {
    id: 6,
    imageURL: "https://source.unsplash.com/800x600/?pizza",
    title: "Margherita Pizza",
    readyInMinutes: 30,
    healthScore: 72,
    difficulty: "Medium",
    extendedIngredients: [
      { id: 1, original: "1 pizza dough" },
      { id: 2, original: "1/2 cup tomato sauce" },
      { id: 3, original: "200g fresh mozzarella" },
      { id: 4, original: "Fresh basil leaves" },
      { id: 5, original: "2 tbsp olive oil" },
      { id: 6, original: "Salt to taste" },
    ],
    instructions:
      "Step 1: Preheat oven with pizza stone. Step 2: Roll out dough. Step 3: Add sauce, mozzarella, and basil. Step 4: Bake until crust is golden. Drizzle with olive oil and serve.",
  },
  {
    id: 7,
    imageURL: "https://source.unsplash.com/800x600/?tacos",
    title: "Chicken Tacos",
    readyInMinutes: 25,
    healthScore: 80,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "2 chicken breasts" },
      { id: 2, original: "1/2 cup tomato sauce" },
      { id: 3, original: "200g fresh mozzarella" },
      { id: 4, original: "Fresh basil leaves" },
      { id: 5, original: "2 tbsp olive oil" },
      { id: 6, original: "Salt to taste" },
    ],
    instructions:
      "Step 1: Preheat oven with pizza stone. Step 2: Roll out dough. Step 3: Add sauce, mozzarella, and basil. Step 4: Bake until crust is golden. Drizzle with olive oil and serve.",
  },
  {
    id: 8,
    imageURL: "https://source.unsplash.com/800x600/?pasta",
    title: "Spaghetti Carbonara",
    readyInMinutes: 25,
    healthScore: 70,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "200g spaghetti" },
      { id: 2, original: "100g pancetta" },
      { id: 3, original: "2 large eggs" },
      { id: 4, original: "50g pecorino cheese" },
      { id: 5, original: "2 cloves garlic" },
      { id: 6, original: "Salt and black pepper to taste" },
    ],
    instructions:
      "Step 1: Cook spaghetti. Step 2: Fry pancetta with garlic. Step 3: Beat eggs and mix with cheese. Step 4: Combine all and season.",
  },
  {
    id: 9,
    imageURL: "https://source.unsplash.com/800x600/?salad",
    title: "Caesar Salad",
    readyInMinutes: 20,
    healthScore: 85,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "1 romaine lettuce" },
      { id: 2, original: "50g croutons" },
      { id: 3, original: "30g parmesan cheese" },
      { id: 4, original: "1 clove garlic" },
      { id: 5, original: "1 egg yolk" },
      { id: 6, original: "2 tbsp olive oil" },
      { id: 7, original: "1 tsp Worcestershire sauce" },
      { id: 8, original: "Juice of 1 lemon" },
      { id: 9, original: "Salt and pepper to taste" },
    ],
    instructions:
      "Step 1: Prepare dressing with egg yolk, garlic, oil, Worcestershire sauce, lemon juice, salt, and pepper. Step 2: Toss lettuce with dressing. Step 3: Top with croutons and shaved parmesan.",
  },
  {
    id: 10,
    imageURL: "https://source.unsplash.com/800x600/?burger",
    title: "Classic Beef Burger",
    readyInMinutes: 30,
    healthScore: 60,
    difficulty: "Medium",
    extendedIngredients: [
      { id: 1, original: "500g ground beef" },
      { id: 2, original: "4 burger buns" },
      { id: 3, original: "4 slices cheddar cheese" },
      { id: 4, original: "1 tomato" },
      { id: 5, original: "Lettuce leaves" },
      { id: 6, original: "1 onion" },
      { id: 7, original: "Salt and pepper to taste" },
      { id: 8, original: "Ketchup and mustard" },
    ],
    instructions:
      "Step 1: Form beef into patties and season. Step 2: Grill patties. Step 3: Assemble burgers with buns, cheese, tomato, lettuce, onion, ketchup, and mustard.",
  },
  {
    id: 11,
    imageURL: "https://source.unsplash.com/800x600/?sushi",
    title: "Sushi Rolls",
    readyInMinutes: 50,
    healthScore: 75,
    difficulty: "Hard",
    extendedIngredients: [
      { id: 1, original: "2 cups sushi rice" },
      { id: 2, original: "4 sheets nori" },
      { id: 3, original: "200g fresh salmon" },
      { id: 4, original: "1 cucumber" },
      { id: 5, original: "Soy sauce" },
      { id: 6, original: "Pickled ginger" },
      { id: 7, original: "Wasabi" },
    ],
    instructions:
      "Step 1: Prepare sushi rice. Step 2: Slice salmon and cucumber. Step 3: Place nori on mat, add rice, salmon, and cucumber. Step 4: Roll tightly and slice. Serve with soy sauce, ginger, and wasabi.",
  },
  {
    id: 12,
    imageURL: "https://source.unsplash.com/800x600/?pancakes",
    title: "Fluffy Pancakes",
    readyInMinutes: 20,
    healthScore: 65,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "1 cup all-purpose flour" },
      { id: 2, original: "2 tbsp sugar" },
      { id: 3, original: "1 tbsp baking powder" },
      { id: 4, original: "1/2 tsp salt" },
      { id: 5, original: "1 cup milk" },
      { id: 6, original: "1 egg" },
      { id: 7, original: "2 tbsp melted butter" },
      { id: 8, original: "Maple syrup" },
    ],
    instructions:
      "Step 1: Mix dry ingredients. Step 2: Whisk wet ingredients and combine with dry. Step 3: Cook pancakes on griddle. Step 4: Serve with maple syrup.",
  },
  {
    id: 13,
    imageURL: "https://source.unsplash.com/800x600/?pizza",
    title: "Margherita Pizza",
    readyInMinutes: 30,
    healthScore: 72,
    difficulty: "Medium",
    extendedIngredients: [
      { id: 1, original: "1 pizza dough" },
      { id: 2, original: "1/2 cup tomato sauce" },
      { id: 3, original: "200g fresh mozzarella" },
      { id: 4, original: "Fresh basil leaves" },
      { id: 5, original: "2 tbsp olive oil" },
      { id: 6, original: "Salt to taste" },
    ],
    instructions:
      "Step 1: Preheat oven with pizza stone. Step 2: Roll out dough. Step 3: Add sauce, mozzarella, and basil. Step 4: Bake until crust is golden. Drizzle with olive oil and serve.",
  },
  {
    id: 14,
    imageURL: "https://source.unsplash.com/800x600/?tacos",
    title: "Chicken Tacos",
    readyInMinutes: 25,
    healthScore: 80,
    difficulty: "Easy",
    extendedIngredients: [
      { id: 1, original: "2 chicken breasts" },
      { id: 2, original: "1/2 cup tomato sauce" },
      { id: 3, original: "200g fresh mozzarella" },
      { id: 4, original: "Fresh basil leaves" },
      { id: 5, original: "2 tbsp olive oil" },
      { id: 6, original: "Salt to taste" },
    ],
    instructions:
      "Step 1: Preheat oven with pizza stone. Step 2: Roll out dough. Step 3: Add sauce, mozzarella, and basil. Step 4: Bake until crust is golden. Drizzle with olive oil and serve.",
  },
];
